// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "product-service",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "getProductsById",
        "description": "",
        "operationId": "getProductsById.get.products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "ProductSchema": {
      "properties": {
        "id": {
          "title": "ProductSchema.id",
          "type": "string"
        },
        "title": {
          "title": "ProductSchema.title",
          "type": "string"
        },
        "description": {
          "title": "ProductSchema.description",
          "type": "string"
        },
        "price": {
          "title": "ProductSchema.price",
          "type": "number"
        }
      },
      "required": [
        "id",
        "title",
        "description",
        "price"
      ],
      "additionalProperties": false,
      "title": "ProductSchema",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "host": "ecjqmbb4ij.execute-api.eu-west-2.amazonaws.com/dev"
};